### ISSUE TITLE
Node RED crash on some commands

### ISSUE THREAD

**Issue by 8666** [damoclark/node-red-contrib-cec#6]
TypeError: _this6.GetLogicalAddresses(...).includes is not a function
    at /root/.node-red/node_modules/node-red-contrib-cec/node_modules/@damoclark/cec-monitor/lib/cec-monitor.js:918:40
    at Array.forEach (native)
    at null._onTimeout (/root/.node-red/node_modules/node-red-contrib-cec/node_modules/@damoclark/cec-monitor/lib/cec-monit                                or.js:915:11)
    at Timer.listOnTimeout (timers.js:89:15)

Will try to find the exact reason

**Comment by 8666** [comment]
When I power on or off the TV with remote I get the same message. Also If I send power ON command from Node RED using:

{"source":null,"target":0,"opcode":"IMAGE_VIEW_ON"}

**Comment by damoclark** [comment]
Hi @8666 

What I have come to learn is that many vendors don't implement the CEC specification correctly and so reliability varies depending on the equipment you use.  I was only really able to test with the devices I had - Panasonic and Sony.  

And unfortunately I don't have time at present to work on issues relating to this module.  

I will however gladly accept PRs and merge them into the codebase if fixes are provided. :)

Damo.

**Comment by 8666** [comment]
I have Philips. I used my own software based on libcec but wanted to move to something more up-to-date and maintained by others as I could not do it myself but ended with the same problem here :)

It is true that many TVs do not behave as expected on some commands. I will try to take a look at your code. Thanks for your node red contribution.

**Comment by 8666** [comment]
I replaced

      if (this.GetLogicalAddresses().includes(t) || phys === null) {
        return
      }

with 

return 

only

at https://github.com/damoclark/cec-monitor/blob/master/src/cec-monitor.js

It is not crashing anymore, still able to get the powerstatus of the TV..not sure what should not work :)

I see there are differnces from https://github.com/senzil/cec-monitor/blob/master/src/cec-monitor.js
